linters-settings:
  govet:
    shadow: true
    settings:
      printf:
        funcs:
          - (github.com/krogertechnology/krogo/pkg/krogo.Log).Printf
          - (github.com/krogertechnology/krogo/pkg/krogo.Log).Debugf
          - (github.com/krogertechnology/krogo/pkg/krogo.Log).Printf
          - (github.com/krogertechnology/krogo/pkg/krogo.Log).Infof
          - (github.com/krogertechnology/krogo/pkg/krogo.Log).Warnf
          - (github.com/krogertechnology/krogo/pkg/krogo.Log).Errorf
          - (github.com/krogertechnology/krogo/pkg/krogo.Log).Fatalf
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  gocognit:
    min-complexity: 20
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  depguard:
    list-type: blacklist
    packages:
      # logging is allowed only by krogo logger, logrus
      # is allowed to use only in that package
      - github.com/sirupsen/logrus
    packages-with-error-messages:
      github.com/sirupsen/logrus: "logging is allowed only by krogo logger"
  misspell:
    locale: US
  goimports:
    local-prefixes: gitlab.kroger.com/inventory/inventory-core
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - wrapperFunc
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
  funlen:
    lines: 100
    statements: 50

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.28.x # use the fixed version to not introduce new linters unexpectedly

issues:
  exclude-dirs:
    - configs
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gochecknoglobals # we use global variables in test to use the same object across tests
        - funlen # due to multiple validations in test, function length cannot be controlled.
        - dupl # large number of duplicate test data blocks ignored
        - gocognit # don't care in tests
        - gocyclo # don't care about complexity in tests
        - godox # ignoring todo comments in tests
        - gosec # ignoring weak random number generator math.rand
  exclude:
    - Using the variable on range scope `tt` in function literal # exclude scope check on table tests (tt)